# Generated by Django 3.2 on 2023-04-15 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_plan.workoutcategory'),
        ),
    ]
